AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"

require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
