AllCops:
  # Should match your gemspec's required_ruby_version minimum
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "bin/**/*"

# Customize your style preferences here
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A#'] # Allow long comment lines

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "**/*.gemspec"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"

# Disable some overly strict cops for gems
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
